urls.py
from django.urls import path

from . import views

app_name = 'support'

urlpatterns = [
    path('create-room/<str:room_id>/', views.create_room, name='create-room'),

    path('chat-admin/', views.chat_admin, name='chat-admin'),

    path('add-user/', views.add_user, name='add-user'),

    path('edit-user/<str:id>/', views.edit_user, name='edit-user'),

    path('room/<str:room_id>/', views.room, name='room'),

    path('delete-room/<str:room_id>/', views.delete_room, name='delete-room'),


]

models.py
from django.db import models
from myauth.models import User

# Create your models here.

class Message(models.Model):
    body = models.TextField()
    sent_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.sent_by.name}-{self.body}'
    
    class Meta:
        ordering = ('created_at',)


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    ROOM_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )

    room_id = models.CharField(max_length=255)
    url = models.CharField(max_length=255, blank=True, null=True)
    messages = models.ManyToManyField(Message, blank=True)

    client = models.ForeignKey(User, related_name='client_rooms', blank=True, null=True, on_delete=models.SET_NULL)
    agent = models.ForeignKey(User, related_name='agent_rooms', blank=True, null=True, on_delete=models.SET_NULL)

    status = models.CharField(max_length=20, choices=ROOM_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.client.name}-{self.room_id}-{self.status}'
    
    class Meta:
        ordering = ('-created_at',)

forms.py
from django import forms

from myauth.models import User


INPUT_CLASSES = 'w-full mb-4 py-4 px-6 rounded-xl text-gray-800 border'

class AddUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role', 'password',)
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email address...',
                'class': INPUT_CLASSES
            }),

            'name': forms.TextInput(attrs={
                'placeholder': 'Name...',
                'class': INPUT_CLASSES
            }),

            'role': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),

            'password': forms.PasswordInput(attrs={
                'placeholder': 'Enter a password...',
                'class': INPUT_CLASSES
            }),
        }


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role',)
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email address...',
                'class': INPUT_CLASSES
            }),

            'name': forms.TextInput(attrs={
                'placeholder': 'Name...',
                'class': INPUT_CLASSES
            }),

            'role': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from .models import Room
from myauth.models import User
from django.contrib.auth.models import Group

from .forms import AddUserForm, EditUserForm

# Create your views here.


@require_POST
@csrf_exempt
@login_required
def create_room(request, room_id):
    url = request.POST.get('url', '')

    room = Room.objects.create(room_id=room_id, client=request.user, url=url)

    return JsonResponse({'message': 'Room Created'})


@login_required
def chat_admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True).filter(is_superuser=False)

    return render(request, 'support/chat_admin.html', {
        'title': 'Chat Rooms',
        'rooms': rooms,
        'users': users,
    })


@login_required
def add_user(request):
    if request.user.has_perm('myauth.add_user'):
        if request.method == 'POST':
            form = AddUserForm(request.POST)

            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(form.cleaned_data['password'])
                user.save()

                if user.role == User.MANAGER:
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)

                    messages.success(request, f'Staff is crated and added to {group.name} group!')

                elif user.role == User.AGENT:
                    group = Group.objects.get(name='Agents')
                    group.user_set.add(user)

                    messages.success(request, f'Staff is crated and added to {group.name} group!')

                else:
                    user.is_staff = False
                    user.save()
                    messages.success(request, 'New client is crated!')

                return redirect ('/support/chat-admin/')
        else:
            form = AddUserForm()

        return render(request, 'support/add_user.html', {
            'title': 'Add user',
            'form': form
        })
    else:
        messages.error(request, 'You do not have access to add staffs!')

        return redirect('/support/chat-admin/')
    

@login_required
def edit_user(request, id):
    if request.user.has_perm('myauth.change_user'):
        user = User.objects.get(pk=id)
        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                user = form.save()

                if user.role == User.MANAGER: 
                    agent_group = Group.objects.get(name='Agents')
                    agent_group.user_set.remove(user)

                    manager_group = Group.objects.get(name='Managers')
                    manager_group.user_set.add(user)

                elif user.role == User.AGENT: 
                    manager_group = Group.objects.get(name='Managers')
                    manager_group.user_set.remove(user)

                    agent_group = Group.objects.get(name='Agents')
                    agent_group.user_set.add(user)

                else:
                    user.is_staff = False
                    user.groups.clear()
                    user.save()

                messages.success(request, 'Staff details updated!')

                return redirect('/support/chat-admin/')
            
        else:
            form = EditUserForm(instance=user)

        return render(request, 'support/edit_user.html', {
            'title': 'Edit Staff',
            'form': form,
        })
    
    else:
        messages.error(request, 'You do not have permission to edit staffs!!')

        return redirect('/support/chat-admin/')


@login_required
def room(request, room_id):
    room = Room.objects.get(room_id=room_id)
    
    if room.status == Room.WAITING:    
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'support/room.html', {
        'title': 'Room',
        'room': room,
    })


@login_required
def delete_room(request, room_id):
    if request.user.has_perm('support.delete_room'):
        room = Room.objects.get(room_id=room_id)
        room.delete()

        messages.success(request, 'Room was deleted!')

        return redirect('/support/chat-admin/')
    
    else:
        messages.error(request, 'You do not have permission to delete rooms!')

        return redirect('/support/chat-admin/')
    

templates/support/add_user.html
{% extends 'core/base.html' %}


{% block title %}{{ title }}{% endblock %}


{% block content %}
    <form method="post" action="." class="w-1/2 mx-auto">
        {% csrf_token %}

        <h1 class="text-2xl text-center mb-10">Add User</h1>

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-300 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>  
        {% endif %}

        <div class="flex justify-center items-center mt-4">
            <button class="py-2 px-6 text-lg bg-gray-600 hover:bg-gray-700 rounded-xl">Add</button>
        </div>
         
    </form>
{% endblock %}

templates/support/chat_admin.html
{% extends 'core/base.html' %}


{% block title %}{{title}}{% endblock %}


{% block content %}

    {% if perms.myauth.view_user %}
        <div class="mt-2">
            <h2 class="mb-4 text-center text-2xl font-semibold">Staffs</h2>

            <a href="{% url 'support:add-user' %}" class="inline-block py-2 px-4 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700">Add Staff</a>

            <div class="mt-6">
                {% for user in users %}
                    <div class="inline-block flex justify-between gap-4 px-3 py-2 {% cycle 'bg-gray-800' '' %}">
                        <p class="w-1/4 px-2 text-center">
                            <a href="">{{ user.name }}</a>
                        </p>

                        <p class="w-1/4 px-2 text-center">{{ user.email }}</p>

                        <p class="w-1/4 px-2 text-center">{{ user.get_role_display }}</p>

                        <p class="w-1/4 px-2 text-center">
                            {% if perms.myauth.change_user %}
                                <a href="{% url 'support:edit-user' user.id %}" class="underline">Edit</a>
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-8 text-center text-2xl font-semibold">Rooms</h2>

        <div class="grid grid-cols-3 gap-4">
            {% for room in rooms %}
                <div class="p-4 rounded-xl {% if room.status == 'waiting' %} bg-emerald-800 {% elif room.status == 'active' %} bg-yellow-800 {% else %} bg-gray-800 {% endif %}">
                    <h3 class="mb-4 text-center text-lg">Chat</h3>

                    <div class="flex flex-col items-center">
                        <div>
                            <p>
                                <b>ID: </b>{{ room.room_id }}<br>
                                <b>Name: </b>{{ room.client.name }}<br>
                                <b>Status: </b>{{ room.get_status_display }}<br>
                                <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
                            </p>
                        </div>

                        <div class="flex justify-between items-center gap-4">
                            <a href="{% url 'support:room' room.room_id %}" class="mt-4 inline-block py-2 px-6 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700">Join</a>
                            <a href="{% url 'support:delete-room' room.room_id %}" class="mt-4 inline-block py-2 px-6 bg-rose-700 text-white rounded-xl hover:bg-rose-800">Delete</a>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/support/edit_user.html
{% extends 'core/base.html' %}


{% block title %}{{ title }}{% endblock %}


{% block content %}
<form method="post" action="." class="w-1/2 mx-auto">
    {% csrf_token %}
    
    <h1 class="text-2xl text-center mb-10">Edit User</h1>

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-300 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>  
    {% endif %}          
    <div class="flex justify-center items-center mt-4">
        <button class="py-2 px-6 text-lg bg-gray-600 hover:bg-gray-700 rounded-xl">Save</button>
    </div>

</form>
{% endblock %}

templates/support/partials/bubble_chat.html
<div id="chat" class="max-w-[350px] fixed right-4 bottom-20">

    <div id="chat_icon" class="w-[60px] h-[60px] rounded-2xl flex justify-center items-center bg-slate-600 border border-black hover:bg-slate-700">
        <button id="chat_open" class="w-full p-4 flex justify-center items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="scale-125 text-white">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
            </svg> 
        </button>
    </div>

    <div id="chat_room" class="hidden w-full p-6 flex flex-col items-center bg-gray-800 rounded-xl">
        
        <div id="chat_log" class="w-full h-[350px] mb-4 p-4 bg-gray-600 rounded-xl overflow-y-scroll">
            <p>Welcome to our support chat! Please send your message and wait for an agent to join. Thank You!</p>
        </div>

        <input id="chat_message_input" type="text" name="name" class="w-full mb-4 py-2 px-4 rounded-xl bg-gray-300 text-black"  placeholder="Type your message...">

        <button id="chat_message_submit" class="py-2 px-4 rounded-xl text-white bg-slate-600 hover:bg-slate-700">Send</button>
        
    </div>

</div>

templates/support/room.html
{% extends 'core/base.html' %}

{% load static chatextras %}


{% block title %}{{ title }}{% endblock %}


{% block content %}

<div class="mb-4">
    <b>Room ID: </b>{{room.room_id}}</br>
    <b>Page: </b>{{room.url}}</br>
    <b>Client: </b>{{room.client.name}}</br>
    <b>Agent: </b>{% firstof room.agent.name 'Not yet...' %}</br>
    <b>Status: </b>{{room.status}}</br>
</div>

<hr>

<div id="chat_log" class="mt-4 p-4 h-[450px] overflow-y-scroll bg-gray-600 rounded-xl">
    {% for message in room.messages.all %}
        <div class="flex w-full max-w-md mt-2 space-x-3 {% if not message.sent_by.role == 'customer' %} ml-auto justify-end {% endif %}">
            
            {% if message.sent_by.role == 'customer' %}
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-800 text-center pt-2">
                    {{message.sent_by.name|initials}}
                </div>
            {% endif %}

                <div>
                    <div class="p-3 {% if not message.sent_by.role == 'customer' %} bg-blue-700 rounded-br-2xl rounded-l-lg {% else %} bg-gray-800 rounded-bl-2xl rounded-r-lg {% endif %}">
                        <p>{{message.body}}</p>
                    </div>

                    <span class="text-xs text-gray-200 leading-none">{{message.created_at|timesince}} ago</span>
                </div>

            {% if not message.sent_by.role == 'customer' %}
                <div class="flex-shrink-0 h-10 w-10 rounded-full bg-blue-700 text-center pt-2">
                    {{message.sent_by.name|initials}}
                </div>
            {% endif %}
            
        </div>
    {% endfor %}
</div>

<hr class="mt-4">

{% if room.status == 'active' %}
<div>
    <input id="chat_message_input" type="text" name="message" class="w-full mt-4 mb-4 py-2 px-4 bg-gray-300 text-black rounded-xl" placeholder="Type your message...">

    <button id="chat_message_submit" class="py-2 px-4 bg-slate-600 rounded-xl hover:bg-slate-700">Send</button>
</div>
{% endif %}

{% endblock %}


{% block scripts %}
    {% if room.status == 'active' %}
        {{room.room_id|json_script:'room_id'}}
        {{request.user.name|json_script:'user_name'}}
        {{request.user.id|json_script:'user_id'}}

        <script src="{% static 'js/main_admin.js' %}"></script>
    {% endif %}
{% endblock %}